### ISSUE TITLE
I would like to add a web design of a clothing line, which was made first on figma and then converted to html, css design

### ISSUE THREAD

**Issue by Niyati3031** [Frey0xD/AllInHacktoberfest#55]
Can you assign this to me for hacktoberfest 2023?

**Comment by Frey0xD** [comment]
Can you share more information about that ? and before making a PR please do that in the suitable folder which is 'WebDev' with your own folder name "clothing line" btw I love the idea

**Comment by Niyati3031** [comment]
https://www.figma.com/proto/PpJISbRol7EscKLM4Tidhh/Fauxica?type=design&node-id=1-2&t=IcmN3XktUlCk5Qv0-1&scaling=min-zoom&page-id=0%3A1&mode=design
here is the figma preview, you can check

**Comment by Frey0xD** [comment]
Nicely done
