### ISSUE TITLE
3d T-shirt designer

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [Frey0xD/AllInHacktoberfest#62]
User can create their own t -shirt and design .
This can be build using javascript .

please assign this to me i am interested to contribute in hacktoberfest_23 : )

**Comment by Bharath-KumarReddy** [comment]
I just now resolved this issue and I already forked this repository , I made a pull request 

Once see the  Pull request Sudoko_Solver in that I added all the code once please check

And merge it  : )

**Comment by Frey0xD** [comment]
That's done ✅

**Comment by Bharath-KumarReddy** [comment]
Can you please change the repo in such a way that it should obey the rules of hacktoberfest_23

As, This PR is excluded due to this repo is not obeying the rules of hacktoberfest
